src/main/java/com/andaily/domain/AbstractDomain.java
/*
 * Copyright (c) 2013 Honyee Industry Group Co., Ltd
 * www.honyee.biz
 * All rights reserved.
 *
 * This software is the confidential and proprietary information of
 * Honyee Industry Group Co., Ltd ("Confidential Information").
 * You shall not disclose such Confidential Information and shall use
 * it only in accordance with the terms of the license agreement you
 * entered into with Honyee Industry Group Co., Ltd.
 */
package com.andaily.domain;

import com.andaily.infrastructure.DateUtils;
import com.andaily.domain.shared.GuidGenerator;
import com.andaily.infrastructure.DateUtils;

import javax.persistence.*;
import java.io.Serializable;
import java.util.Date;

/**
 * @author Shengzhao Li
 */
@MappedSuperclass
public abstract class AbstractDomain implements Serializable {

    private static final long serialVersionUID = 913921286328215144L;
    /**
     * Database id
     */
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    protected int id;

    @Column(name = "archived", columnDefinition = "tinyint(1)")
    protected boolean archived;

    @Version
    @Column(name = "version")
    protected int version;
    /**
     * Domain business guid.
     */
    @Column(name = "guid", unique = true)
    protected String guid = GuidGenerator.generate();

    /**
     * The domain create time.
     */
    @Column(name = "create_time")
//    @Type(type = "org.hibernate.type.TimestampType")
    protected Date createTime = DateUtils.now();

    public AbstractDomain() {
    }

    public int id() {
        return id;
    }

    public void id(int id) {
        this.id = id;
    }

    public boolean archived() {
        return archived;
    }

    public AbstractDomain archived(boolean archived) {
        this.archived = archived;
        return this;
    }

    public String guid() {
        return guid;
    }

    public void guid(String guid) {
        this.guid = guid;
    }

    public Date createTime() {
        return createTime;
    }

    public boolean isNewly() {
        return id == 0;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (!(o instanceof AbstractDomain)) {
            return false;
        }
        AbstractDomain that = (AbstractDomain) o;
        return guid.equals(that.guid);
    }

    @Override
    public int hashCode() {
        return guid.hashCode();
    }


    @Override
    public String toString() {
        final StringBuilder sb = new StringBuilder();
        sb.append("{id=").append(id);
        sb.append(", archived=").append(archived);
        sb.append(", version=").append(version);
        sb.append(", guid='").append(guid).append('\'');
        sb.append(", createTime=").append(createTime);
        sb.append('}');
        return sb.toString();
    }
}

src/main/webapp/WEB-INF/jsp/instance/instance_form.jsp

<%--
 * 
 * @author Shengzhao Li
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<!DOCTYPE HTML>
<html>
<head>
    <title>${formDto.newly?'New':'Edit'} Instance</title>
</head>
<body>
<div>
    <div class="row">
        <div class="col-md-12">
            <h4>${formDto.newly?'New':'Edit'} Instance</h4>
            <form:form commandName="formDto" cssClass="form-horizontal">
                <div class="form-group">
                    <label for="instanceName" class="col-sm-2 control-label">Instance name</label>

                    <div class="col-sm-8">
                        <form:input path="instanceName" id="instanceName" cssClass="form-control"
                                    placeholder="Input instance name" required="true"/>
                        <p class="help-block">An unique name of the application instance</p>
                        <form:errors path="instanceName" cssClass="text-danger"/>
                    </div>
                </div>
                <div class="form-group">
                    <label for="monitorUrl" class="col-sm-2 control-label">URL</label>

                    <div class="col-sm-8">
                        <form:input path="monitorUrl" id="monitorUrl" cssClass="form-control"
                                    placeholder="The application monitoring url" required="true"/>
                        <p class="help-block">Start with 'http' or 'https', e.g. 'http://andaily.com/test.html'; URL
                            request method: GET</p>
                        <form:errors path="monitorUrl" cssClass="text-danger"/>
                    </div>
                </div>
                <div class="form-group">
                    <label for="monitorUrl" class="col-sm-2 control-label">Frequency(s)</label>

                    <div class="col-sm-8">
                        <form:select path="frequency" id="frequency" cssClass="form-control">
                            <form:options items="${formDto.frequencies}" itemLabel="seconds" itemValue="value"/>
                        </form:select>
                        <p class="help-block">The seconds interval between the two requests</p>
                        <form:errors path="frequency" cssClass="text-danger"/>
                    </div>
                </div>
                <div class="form-group">
                    <label for="maxConnectionSeconds" class="col-sm-2 control-label"><abbr
                            title='Max Connection Time(ms)'>Max Conn(s)</abbr></label>

                    <div class="col-sm-8">
                        <form:input path="maxConnectionSeconds" id="maxConnectionSeconds" cssClass="form-control"
                                    placeholder="Input max connection time(ms)" required="true"/>
                        <p class="help-block">Max connection time when send request every time, default max is Frequency
                            seconds</p>
                        <form:errors path="maxConnectionSeconds" cssClass="text-danger"/>
                    </div>
                </div>
                <div class="form-group">
                    <label for="email" class="col-sm-2 control-label">Email</label>

                    <div class="col-sm-8">
                        <form:input path="email" id="email" cssClass="form-control"
                                    placeholder="Input email" required="true"/>
                        <p class="help-block">The email that use when monitoring the application response exception,
                            will send email to the address; More split by (;)</p>
                        <form:errors path="email" cssClass="text-danger"/>
                    </div>
                </div>
                <div class="form-group">
                    <label for="remark" class="col-sm-2 control-label">Remark</label>

                    <div class="col-sm-8">
                        <form:textarea path="remark" id="remark" rows="3"
                                       cssClass="form-control"
                                       placeholder="Remark information of the instance"/>
                        <p class="help-block">More information of the instance; Optional</p>
                        <form:errors path="remark" cssClass="text-danger"/>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-success"><em class="fui-check-circle"></em> Save</button>
                        &nbsp;<a href="list.hb">Cancel</a>
                    </div>
                </div>
            </form:form>
        </div>
    </div>
</div>

<script>
    $(function () {
        new InstanceForm();
    });
</script>
</body>
</html>

src/main/webapp/WEB-INF/jsp/instance/instance_list.jsp

<%--
 * 
 * @author Shengzhao Li
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="dis" uri="http://displaytag.sf.net" %>
<%@ taglib tagdir="/WEB-INF/tags" prefix="custom" %>
<!DOCTYPE HTML>
<html>
<head>
    <title>Instances</title>

    <style>
        ul li:hover {
            background-color: #f9f9f9;
        }
    </style>
</head>
<body>
<%--Alert--%>
<div class="row">
    <div class="col-md-12">
        <div class="alert alert-success" style="display: none;">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <div><em class="fui-check-circle"></em>
                <span id="saveInstanceOK" style="display: none;">Save instance successful</span>
                <span id="enableSuccess" style="display: none;">Enable instance heart-beat successful</span>
                <span id="stopSuccess" style="display: none;">Stop instance heart-beat successful</span>
                <span id="deleteSuccess" style="display: none;">Delete instance successful</span>
            </div>
        </div>
        <div class="alert alert-danger" style="display: none;">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <div><em class="fui-check-circle"></em>
                <span id="enableFailed" style="display: none;">Fail to enable instance heart-beat monitoring; Please checking server-console what happening...</span>
                <span id="stopFailed" style="display: none;">Fail to stop instance heart-beat monitoring; Please checking server-console what happening...</span>
                <span id="deleteFailed"
                      style="display: none;">Delete instance failed; Make sure it is not-enabled</span>
            </div>
        </div>

    </div>
</div>
<div class="row">
    <div class="col-md-4">
        <form class="form-inline" role="form" action="" id="filterForm">
            <div class="input-group">
                <input type="text" name="instanceName" class="form-control" id="instanceName"
                       placeholder="Instance name" value="${listDto.instanceName}"/>
                <span class="input-group-btn">
                    <button type="submit" class="btn"><i class="fui-search"></i></button>
                </span>
            </div>
            <strong>${listDto.totalSize}</strong> instance(s)
        </form>
    </div>
    <div class="col-md-2">
        &nbsp;
    </div>
    <div class="col-md-4 col-md-offset-2">
        <div class="pull-right">
            <a href="instance_form.hb" class="btn btn-primary"><i class="fui-plus"></i> New Instance</a>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <br/>
        <c:if test="${empty listDto.list}">
            <div class="alert alert-info" role="alert">
                <strong class="fui-info-circle"></strong>
                Not yet add any instances, please click 'New Instance' to add the first instance.
            </div>
        </c:if>
        <c:if test="${not empty listDto.list}">
            <ul class="list-group">
                <c:forEach items="${listDto.list}" var="d" varStatus="sta">
                    <custom:instance_group_item d="${d}"/>
                </c:forEach>
            </ul>
            <%--pagination--%>
            <dis:table list="${listDto}" id="d" form="filterForm" class="table table-striped table-hover hidden">
                <dis:column property="frequency.seconds"/>
            </dis:table>
        </c:if>
    </div>
</div>
<script>
    $(function () {
        new InstanceList('${param.alert}');
    })
</script>
</body>
</html>

src/main/webapp/WEB-INF/jsp/instance/statistics_instance.jsp
<%--
 * 
 * @author Shengzhao Li
--%>

<%@ page contentType="text/html;charset=UTF-8" language="java" %>


<ul class="list-group">
    <li class="list-group-item">
        Normal connection: <span class="text-success">${statisticsDto.normalConnection}</span>
    </li>
    <li class="list-group-item">
        Last can not connection: <a href="../log/list.hb?instanceGuid=${statisticsDto.guid}&normal=2"><span
            class="text-danger">${statisticsDto.lastNotNormalTime}</span></a>
    </li>
    <li class="list-group-item">
        Connections normal/not-normal times: <a href="../log/list.hb?instanceGuid=${statisticsDto.guid}&normal=1"><span
            class="text-info">${statisticsDto.normalAmount}</span></a> / <a
            href="../log/list.hb?instanceGuid=${statisticsDto.guid}&normal=2"><span
            class="text-danger">${statisticsDto.notNormalAmount}</span></a>
    </li>
    <li class="list-group-item">
        Interrupt connection times: <a href="../log/reminder_list.hb?instanceGuid=${statisticsDto.guid}&normal=0"><span
            class="text-info">${statisticsDto.interruptTime}</span></a>
    </li>
    <li class="list-group-item">
        Send reminder times: <a href="../log/reminder_list.hb?instanceGuid=${statisticsDto.guid}&normal=1"><span
            class="text-info">${statisticsDto.sendReminderTime}</span></a>
    </li>
</ul>